# Generated by Django 2.2.11 on 2020-03-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='hghghghg',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
